package py.edu.ucsa.sisalews.exception;

public enum ErrorCode {
	NO_ERROR,
	INTERNAL_ERROR,
	PARSING_ERROR,
	IO_ERROR,
	JSON_ENCODING_ERROR,
	JSON_DECODING_ERROR,
	PARAMETER_ERROR,		 
	NO_DATA_FOUND, 
	UNAUTHORIZED, 
	UNSUPPORTED_OPERATION, 
	DATA_INTEGRITY_VIOLATION, 
	DATA_ACCESS_EXCEPTION, 
	NOT_IMPLEMENTED_EXCEPTION, 
	INVALID_REQUEST, 
	VALIDATION_FAILED	
}